# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "semaphore-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi==2020.4.5.1",
    "six==1.14.0",
    "urllib3==1.25.8",
    "setuptools==46.1.3"
]

setup(
    name=NAME,
    version=VERSION,
    description="SEMAPHORE",
    author_email="S.Koulouzis@uva.nl",
    url="https://github.com/QCDIS/semaphore-python-client",
    keywords=["Swagger", "SEMAPHORE"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    long_description="""\
    Semaphore API  # noqa: E501
    """
)
