# coding: utf-8

"""
    SQE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import qumranica_api_connector
from qumranica_api_connector.models.image_dto import ImageDTO  # noqa: E501
from qumranica_api_connector.rest import ApiException

class TestImageDTO(unittest.TestCase):
    """ImageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImageDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = qumranica_api_connector.models.image_dto.ImageDTO()  # noqa: E501
        if include_optional :
            return ImageDTO(
                image_to_image_map_editor_id = 56, 
                region_in_master_image = '0', 
                region_in_image = '0', 
                transform_to_master = '0', 
                id = 56, 
                url = '0', 
                lighting_type = null, 
                lighting_direction = null, 
                wave_length = [
                    '0'
                    ], 
                type = '0', 
                side = null, 
                ppi = 56, 
                master = True, 
                catalog_number = 56
            )
        else :
            return ImageDTO(
                id = 56,
                url = '0',
                lighting_type = null,
                lighting_direction = null,
                wave_length = [
                    '0'
                    ],
                type = '0',
                side = null,
                ppi = 56,
                master = True,
                catalog_number = 56,
        )

    def testImageDTO(self):
        """Test ImageDTO"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
