""" country groups vocabularies """

COUNTRY_GROUPS = {
    (u'CA5', u'Central Asia'): [
        u'Kyrgyzstan',
        u'Kazakhstan',
        u'Tajikistan',
        u'Turkmenistan',
        u'Uzbekistan'
    ],

    (u'EN7', u'Eastern neighbours'): [
        u'Armenia',
        u'Azerbaijan',
        u'Belarus',
        u'Georgia',
        u'Moldova',
        u'Russia',
        u'Ukraine'
    ],

    (u'EFTA4', u'European Free Trade Association'): [
      u'Switzerland', u'Iceland', u'Liechtenstein', u'Norway'
    ],

    (u'EU', u'European Union'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czechia',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Croatia',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    (u'EU12', u'EU12'): [
        u'Belgium',
        u'Denmark',
        u'France',
        u'Germany',
        u'Greece',
        u'Ireland',
        u'Italy',
        u'Luxembourg',
        u'Netherlands',
        u'Portugal',
        u'Spain',
        u'United Kingdom',
    ],

    (u'EU15', u'EU15'): [
         u'Portugal',
         u'Spain',
         u'Denmark',
         u'United Kingdom',
         u'Sweden',
         u'Netherlands',
         u'Austria',
         u'Belgium',
         u'Germany',
         u'Luxembourg',
         u'Ireland',
         u'France',
         u'Italy',
         u'Greece',
         u'Finland'
    ],

    (u'EU25', u'EU25'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czechia',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Poland'
    ],

    (u'EU27', u'EU27'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czechia',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    (u'EU28', u'EU28'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czechia',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Croatia',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    (u'EUN22', u'EU neighbours and their neighbours'): [
        u'Armenia',
        u'Azerbaijan',
        u'Belarus',
        u'Algeria',
        u'Egypt',
        u'Georgia',
        u'Israel',
        u'Jordan',
        u'Kyrgyzstan',
        u'Kazakhstan',
        u'Lebanon',
        u'Libya',
        u'Morocco',
        u'Moldova',
        u'Palestine',
        u'Russia',
        u'Syria',
        u'Tajikistan',
        u'Turkmenistan',
        u'Tunisia',
        u'Ukraine',
        u'Uzbekistan'
    ],

    (u'EEA', u'EEA Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czechia',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey'
    ],

    (u'EEA32', u'EEA-32 Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Czechia',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
    ],

    (u'EEA33', u'EEA-33 Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czechia',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
    ],

    (u'EIONET', u'Eionet'): [
        u'Albania',
        u'Austria',
        u'Bosnia and Herzegovina',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czechia',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Montenegro',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Serbia',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
        u'North Macedonia',
    ],

    (u'NMS10', u'New Member States (10 countries)'): [
        u'Cyprus',
        u'Czechia',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Slovenia',
        u'Slovakia'
    ],

    (u'NMS12', u'New Member States (12 countries)'): [
        u'Bulgaria',
        u'Cyprus',
        u'Czechia',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Romania',
        u'Slovenia',
        u'Slovakia'
    ],

    (u'NMS13', u'New Member States (13 countries)'): [
        u'Bulgaria',
        u'Croatia',
        u'Cyprus',
        u'Czechia',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Romania',
        u'Slovenia',
        u'Slovakia'
    ],

    (u'SN10', u'Southern neighbours'): [
        u'Algeria',
        u'Egypt',
        u'Israel',
        u'Jordan',
        u'Lebanon',
        u'Libya',
        u'Morocco',
        u'Palestine',
        u'Syria',
        u'Tunisia'
    ],

    (u'WB6', u'West Balkan 6'): [
        u'Albania',
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'North Macedonia',
        u'Serbia'
    ],

    (u'WB7', u'West Balkan 7'): [
        u'Albania',
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'Kosovo (UNSCR 1244/99)',
        u'North Macedonia',
        u'Serbia'
    ],

    (u'YU', u'Former republics of Yugoslavia'): [
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'North Macedonia',
        u'Serbia',
        u'Slovenia',
        u'Kosovo (UNSCR 1244/99)'
    ],
    (u'PANE', u'Pan-Europe'): [
        u'Cyprus',
        u'Estonia',
        u'Poland',
        u'Denmark',
        u'Luxembourg',
        u'Ireland',
        u'Netherlands',
        u'Belgium',
        u'Latvia',
        u'Malta',
        u'Germany',
        u'Czechia',
        u'Hungary',
        u'Bulgaria',
        u'Sweden',
        u'Greece',
        u'Portugal',
        u'Spain',
        u'Italy',
        u'Austria',
        u'Finland',
        u'Romania',
        u'United Kingdom',
        u'France',
        u'Lithuania',
        u'Slovenia',
        u'Slovakia',
        u'Switzerland',
        u'Iceland',
        u'Liechtenstein',
        u'Norway',
        u'Turkey',
        u'Albania',
        u'Armenia',
        u'Azerbaijan',
        u'Belarus',
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'North Macedonia',
        u'Georgia',
        u'Kazakhstan',
        u'Kyrgyzstan',
        u'Kosovo (UNSCR 1244/99)',
        u'Monaco',
        u'Montenegro',
        u'Moldova',
        u'Russia',
        u'San Marino',
        u'Serbia',
        u'Tajikistan',
        u'Turkmenistan',
        u'Ukraine',
        u'Uzbekistan'
    ]

}
