
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-15T11:56:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f886e3c4e9e99e70a621e7863c68739c74e38bac",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
