# Generated by Django 2.2.16 on 2020-10-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_community', '0007_auto_20201012_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycircle',
            name='allow_create_backlink',
        ),
        migrations.RemoveField(
            model_name='communitycircle',
            name='is_backlink',
        ),
        migrations.RemoveField(
            model_name='communitycircle',
            name='urlid',
        ),
        migrations.RemoveField(
            model_name='communityjoboffer',
            name='allow_create_backlink',
        ),
        migrations.RemoveField(
            model_name='communityjoboffer',
            name='is_backlink',
        ),
        migrations.RemoveField(
            model_name='communityjoboffer',
            name='urlid',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='allow_create_backlink',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='is_backlink',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='urlid',
        ),
        migrations.RemoveField(
            model_name='communityproject',
            name='allow_create_backlink',
        ),
        migrations.RemoveField(
            model_name='communityproject',
            name='is_backlink',
        ),
        migrations.RemoveField(
            model_name='communityproject',
            name='urlid',
        ),
        migrations.AlterField(
            model_name='communitycircle',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_community.Community'),
        ),
        migrations.AlterField(
            model_name='communityjoboffer',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_community.Community'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_community.Community'),
        ),
        migrations.AlterField(
            model_name='communityproject',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_community.Community'),
        ),
    ]
