# Generated by Django 3.1.1 on 2020-09-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_oci", "0003_auto_20200920_2237"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("key", "image")},
        ),
    ]
