from kryptal.pluginmanager.IFilesystem import IFilesystem, MountedFilesystem
from typing import List, Dict, Any


class DummyFilesystem(IFilesystem):
    def name(self) -> str: ...
    async def create_and_mount(self, ciphertextDir: str, plaintextDir: str, password: bytes) -> None: ...
    async def mount(self, ciphertextDir: str, plaintextDir: str, password: bytes) -> None: ...
    async def unmount(self, plaintextDir: str) -> None: ...
    async def mounted_filesystems(self) -> List[MountedFilesystem]: ...
