# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grr_response_proto/semantic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grr_response_proto/semantic.proto',
  package='grr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n!grr_response_proto/semantic.proto\x12\x03grr\x1a google/protobuf/descriptor.proto\"\xb7\x01\n\x12SemanticDescriptor\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0c\x64ynamic_type\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12-\n\x05label\x18\x03 \x03(\x0e\x32\x1e.grr.SemanticDescriptor.Labels\x12\x15\n\rfriendly_name\x18\x04 \x01(\t\"\"\n\x06Labels\x12\x0c\n\x08\x41\x44VANCED\x10\x01\x12\n\n\x06HIDDEN\x10\x02\"E\n\x19SemanticMessageDescriptor\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x13\n\x0bunion_field\x18\x02 \x01(\t:K\n\x08sem_type\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xbf\xcc\x18 \x01(\x0b\x32\x17.grr.SemanticDescriptor:T\n\x08semantic\x12\x1f.google.protobuf.MessageOptions\x18\xcb\xbf\xcc\x18 \x01(\x0b\x32\x1e.grr.SemanticMessageDescriptor:9\n\x0b\x64\x65scription\x12!.google.protobuf.EnumValueOptions\x18\x9d\xb7\x99\x17 \x01(\t:S\n\x05label\x12!.google.protobuf.EnumValueOptions\x18\x9e\xb7\x99\x17 \x03(\x0e\x32\x1e.grr.SemanticDescriptor.Labels'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


SEM_TYPE_FIELD_NUMBER = 51584972
sem_type = _descriptor.FieldDescriptor(
  name='sem_type', full_name='grr.sem_type', index=0,
  number=51584972, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
SEMANTIC_FIELD_NUMBER = 51584971
semantic = _descriptor.FieldDescriptor(
  name='semantic', full_name='grr.semantic', index=1,
  number=51584971, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DESCRIPTION_FIELD_NUMBER = 48651165
description = _descriptor.FieldDescriptor(
  name='description', full_name='grr.description', index=2,
  number=48651165, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
LABEL_FIELD_NUMBER = 48651166
label = _descriptor.FieldDescriptor(
  name='label', full_name='grr.label', index=3,
  number=48651166, type=14, cpp_type=8, label=3,
  has_default_value=False, default_value=[],
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

_SEMANTICDESCRIPTOR_LABELS = _descriptor.EnumDescriptor(
  name='Labels',
  full_name='grr.SemanticDescriptor.Labels',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADVANCED', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIDDEN', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_SEMANTICDESCRIPTOR_LABELS)


_SEMANTICDESCRIPTOR = _descriptor.Descriptor(
  name='SemanticDescriptor',
  full_name='grr.SemanticDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='grr.SemanticDescriptor.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_type', full_name='grr.SemanticDescriptor.dynamic_type', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='grr.SemanticDescriptor.description', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='grr.SemanticDescriptor.label', index=3,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friendly_name', full_name='grr.SemanticDescriptor.friendly_name', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEMANTICDESCRIPTOR_LABELS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=260,
)


_SEMANTICMESSAGEDESCRIPTOR = _descriptor.Descriptor(
  name='SemanticMessageDescriptor',
  full_name='grr.SemanticMessageDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='grr.SemanticMessageDescriptor.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='union_field', full_name='grr.SemanticMessageDescriptor.union_field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=331,
)

_SEMANTICDESCRIPTOR.fields_by_name['label'].enum_type = _SEMANTICDESCRIPTOR_LABELS
_SEMANTICDESCRIPTOR_LABELS.containing_type = _SEMANTICDESCRIPTOR
DESCRIPTOR.message_types_by_name['SemanticDescriptor'] = _SEMANTICDESCRIPTOR
DESCRIPTOR.message_types_by_name['SemanticMessageDescriptor'] = _SEMANTICMESSAGEDESCRIPTOR
DESCRIPTOR.extensions_by_name['sem_type'] = sem_type
DESCRIPTOR.extensions_by_name['semantic'] = semantic
DESCRIPTOR.extensions_by_name['description'] = description
DESCRIPTOR.extensions_by_name['label'] = label
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemanticDescriptor = _reflection.GeneratedProtocolMessageType('SemanticDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _SEMANTICDESCRIPTOR,
  '__module__' : 'grr_response_proto.semantic_pb2'
  # @@protoc_insertion_point(class_scope:grr.SemanticDescriptor)
  })
_sym_db.RegisterMessage(SemanticDescriptor)

SemanticMessageDescriptor = _reflection.GeneratedProtocolMessageType('SemanticMessageDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _SEMANTICMESSAGEDESCRIPTOR,
  '__module__' : 'grr_response_proto.semantic_pb2'
  # @@protoc_insertion_point(class_scope:grr.SemanticMessageDescriptor)
  })
_sym_db.RegisterMessage(SemanticMessageDescriptor)

sem_type.message_type = _SEMANTICDESCRIPTOR
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(sem_type)
semantic.message_type = _SEMANTICMESSAGEDESCRIPTOR
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(semantic)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(description)
label.enum_type = _SEMANTICDESCRIPTOR_LABELS
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(label)

# @@protoc_insertion_point(module_scope)
