# Generated by Django 2.2.4 on 2019-12-11 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0005_ore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ore_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moonstuff.Ore'),
        ),
    ]
