# Generated by Django 2.0.13 on 2019-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0006_auto_20191211_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ore',
            name='unit_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ore',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
