#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['phys', 'phys.examples']

package_data = \
{'': ['*']}

install_requires = \
['pyxel >= 1.4.0']

setup(name='pyxel-physics',
      version='0.1.0',
      description='Physics module that merges Pymunk with Pyxel.',
      author='Fábio Macêdo Mendes',
      author_email='fabiomacedomendes@gmail.com',
      url='https://github.com/fisjogos-fga/pyxel-physics',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
