# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/example_gen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx/proto/example_gen.proto',
  package='tfx.components.example_gen',
  syntax='proto3',
  serialized_pb=_b('\n\x1btfx/proto/example_gen.proto\x12\x1atfx.components.example_gen\x1a\x19google/protobuf/any.proto\"h\n\x05Input\x12\x37\n\x06splits\x18\x01 \x03(\x0b\x32\'.tfx.components.example_gen.Input.Split\x1a&\n\x05Split\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t\";\n\x0c\x43ustomConfig\x12+\n\rcustom_config\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"Y\n\x06Output\x12=\n\x0csplit_config\x18\x03 \x01(\x0b\x32\'.tfx.components.example_gen.SplitConfigJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05\"\x85\x01\n\x0bSplitConfig\x12=\n\x06splits\x18\x01 \x03(\x0b\x32-.tfx.components.example_gen.SplitConfig.Split\x1a\x31\n\x05Split\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0chash_buckets\x18\x02 \x01(\rJ\x04\x08\x03\x10\x04J\x04\x08\x02\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INPUT_SPLIT = _descriptor.Descriptor(
  name='Split',
  full_name='tfx.components.example_gen.Input.Split',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tfx.components.example_gen.Input.Split.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='tfx.components.example_gen.Input.Split.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=190,
)

_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='tfx.components.example_gen.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='splits', full_name='tfx.components.example_gen.Input.splits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INPUT_SPLIT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=190,
)


_CUSTOMCONFIG = _descriptor.Descriptor(
  name='CustomConfig',
  full_name='tfx.components.example_gen.CustomConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='custom_config', full_name='tfx.components.example_gen.CustomConfig.custom_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=251,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='tfx.components.example_gen.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='split_config', full_name='tfx.components.example_gen.Output.split_config', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=342,
)


_SPLITCONFIG_SPLIT = _descriptor.Descriptor(
  name='Split',
  full_name='tfx.components.example_gen.SplitConfig.Split',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tfx.components.example_gen.SplitConfig.Split.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash_buckets', full_name='tfx.components.example_gen.SplitConfig.Split.hash_buckets', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=472,
)

_SPLITCONFIG = _descriptor.Descriptor(
  name='SplitConfig',
  full_name='tfx.components.example_gen.SplitConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='splits', full_name='tfx.components.example_gen.SplitConfig.splits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SPLITCONFIG_SPLIT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=478,
)

_INPUT_SPLIT.containing_type = _INPUT
_INPUT.fields_by_name['splits'].message_type = _INPUT_SPLIT
_CUSTOMCONFIG.fields_by_name['custom_config'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_OUTPUT.fields_by_name['split_config'].message_type = _SPLITCONFIG
_SPLITCONFIG_SPLIT.containing_type = _SPLITCONFIG
_SPLITCONFIG.fields_by_name['splits'].message_type = _SPLITCONFIG_SPLIT
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['CustomConfig'] = _CUSTOMCONFIG
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['SplitConfig'] = _SPLITCONFIG

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(

  Split = _reflection.GeneratedProtocolMessageType('Split', (_message.Message,), dict(
    DESCRIPTOR = _INPUT_SPLIT,
    __module__ = 'tfx.proto.example_gen_pb2'
    # @@protoc_insertion_point(class_scope:tfx.components.example_gen.Input.Split)
    ))
  ,
  DESCRIPTOR = _INPUT,
  __module__ = 'tfx.proto.example_gen_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.example_gen.Input)
  ))
_sym_db.RegisterMessage(Input)
_sym_db.RegisterMessage(Input.Split)

CustomConfig = _reflection.GeneratedProtocolMessageType('CustomConfig', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMCONFIG,
  __module__ = 'tfx.proto.example_gen_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.example_gen.CustomConfig)
  ))
_sym_db.RegisterMessage(CustomConfig)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUT,
  __module__ = 'tfx.proto.example_gen_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.example_gen.Output)
  ))
_sym_db.RegisterMessage(Output)

SplitConfig = _reflection.GeneratedProtocolMessageType('SplitConfig', (_message.Message,), dict(

  Split = _reflection.GeneratedProtocolMessageType('Split', (_message.Message,), dict(
    DESCRIPTOR = _SPLITCONFIG_SPLIT,
    __module__ = 'tfx.proto.example_gen_pb2'
    # @@protoc_insertion_point(class_scope:tfx.components.example_gen.SplitConfig.Split)
    ))
  ,
  DESCRIPTOR = _SPLITCONFIG,
  __module__ = 'tfx.proto.example_gen_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.example_gen.SplitConfig)
  ))
_sym_db.RegisterMessage(SplitConfig)
_sym_db.RegisterMessage(SplitConfig.Split)


# @@protoc_insertion_point(module_scope)
