# Generated by Django 3.1.1 on 2020-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
