# Generated by Django 3.1.1 on 2020-09-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0003_picturepost_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturepost',
            name='url_height',
            field=models.PositiveIntegerField(default=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='picture',
            field=models.ImageField(height_field='url_height', upload_to=''),
        ),
    ]
