# Generated by Django 3.1.1 on 2020-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_auto_20200923_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturepost',
            name='url_width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='picture',
            field=models.ImageField(height_field='url_height', upload_to='', width_field='url_width'),
        ),
    ]
