# Generated by Django 3.1.1 on 2020-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0005_auto_20200923_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Publication date'),
        ),
    ]
