# Generated by Django 3.1.1 on 2020-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_auto_20200923_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='description',
            field=models.TextField(),
        ),
    ]
