
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-10-15T18:36:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e352e739b30a722cd8c35bc86942a759981606bb",
 "version": "0.94.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
