"""
Print random joke.
"""

from channeling import message_formatting as mf
from channeling.config import ChannelingConfig

import asyncio
import random

conf = ChannelingConfig()

jokes_list = [
    "How does a rabbi make coffee? Hebrews it!",
    "Rest in peace boiling water. You will be mist!",
    "How do you throw a space party? You planet!",
    "Want to hear a construction joke? Oh never mind, I'm still working on that one.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I hate Russian dolls… they're so full of themselves!",
    "Talk is cheap? Have you ever talked to a lawyer?",
    "Why did the gym close down? It just didn't work out!",
    "Two artists had an art contest. It ended in a draw!",
    "A plateau is the highest form of flattery.",
    "I have a fear of speed bumps. But I am slowly getting over it.",
    "You can only get spoiled milk from a pampered cow.",
    "What do you call a boomerang that doesn't come back? A stick!",
    "You know what I saw today? Everything I looked at.",
    "What are shark's two most favorite words? Man overboard!",
    "If we shouldn't eat at night, why do they put a light in the fridge?",
    "Have you ever tried eating a clock? It's really time-consuming, especially if you go for seconds.",
    "Why are ghosts such bad liars? Because they are easy to see through.",
    "It's cleaning day so naturally, I've already polished off a whole chocolate bar.",
    "What did the buffalo say when his son left for college? Bison!",
    "Here, I bought you a calendar. Your days are numbered now.",
    "Where do fish sleep? In the riverbed.",
    "What did one plate say to his friend? Tonight, dinner's on me!",
    "Where are average things manufactured? The satisfactory.",
    "I tried to sure the airport for misplacing my luggage. I lost my case.",
    "What kind of exercise do lazy people do? Diddly-squats.",
    "What do you call a pony with a cough? A little horse!",
    "What is Forest Gump's password? 1Forest1.",
    "Why did the M&M go to school? He wanted to be a Smartie.",
    "What did one traffic light say to the other? Stop looking! I am changing!",
    "What do you call bears with no ears? B.",
    "What's a foot long and slippery? A slipper!",
    "Why do French people eat snails? They don't like fast food!",
    "What's red and moves up and down? A tomato in an elevator!",
    "I invented a new word today. Plagiarism.",
    "What is sticky and brown? A stick!",
    "Why doesn't the sun go to college? Because it has a million degrees!",
    "I was wondering why the frisbee was getting bigger, then it hit me.",
    "I have many jokes about unemployed people, sadly none of them work.",
    "What do you call a singing laptop? A Dell!",
    "Why was six afraid of seven? Because seven ate nine.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "How do trees get online? They just log on!",
    "Some people think prison is one word…but to robbers it's the whole sentence.",
    "My girlfriend treats me like God. She ignores my existence and only talks to me when she needs something.",
    "Where does the sheep get his hair cut? The baa baa shop!",
    "Why did the orange stop? It ran out of juice!",
    "I never make mistakes. …I thought I did once; but I was wrong.",
    "What dd the man in the moon do when his hair got too long? Eclipse it!",
    "What did 0 say to 8? Nice belt!",
    # ----------------------------------------------------------------------------------
    "What do you call an Argentinian with a rubber toe?\nRoberto",
    "I am terrified of elevators,\nI'm going to start taking steps to avoid them",
    "Why do crabs never give to charity?\nBecause they're shellfish.",
    "Why don't skeletons ever go trick or treating?\nBecause they have no body to go with",
    "What do you call cheese by itself?\nProvolone",
    "Ill call you later.\nDon't call me later, call me Dad",
    "Dad, I'm hungry.\nHello, Hungry. I'm Dad",
    "Where does Fonzie like to go for lunch?\nChick-Fil-Eyyyyyyyy",
    "Did you hear about the cheese factory that exploded in France?\nThere was nothing left but de Brie",
    "I knew I shouldn’t have had the seafood\nI’m feeling a little eel",
    "What do you call a sketchy Italian neighbour hood?\nThe Spaghetto",
    "Why can't you have a nose 12 inches long?\nBecause then it would be a foot",
    "My wife is on a tropical food diet, the house is full of the stuff\nIt's enough to make a mango crazy",
    "I’d like to give a big shout out to all the sidewalks\nfor keeping me off the streets",
    "What does an annoying pepper do?\nIt get’s jalapeño face",
    "Why did the scarecrow win an award?\nBecause he was outstanding in his field",
    "Why do bees hum?\nBecause they don't know the words",
    "What do prisoners use to call each other?\nCell phones",
    "What do you call cheese that isn't yours?\nNacho Cheese",
    "What do you get when you cross a snowman with a vampire\nFrostbite",
    "What lies at the bottom of the ocean and twitches?\nA nervous wreck",
    "Why couldn't the bicycle stand up by itself?\nIt was two tired",
    "What did the grape do when he got stepped on?\nHe let out a little wine",
    "I've just been diagnosed as colorblind\nI know, it certainly has come out of the purple",
    "Last night I dreamt I was a muffler\nI woke up exhausted",
    "What do you call a deer with no eyes?\nNo idea",
    "I just watched a program about beavers\nIt was the best dam program I've ever seen",
    "Two satellites decided to get married\nThe wedding wasn't much, but the reception was incredible",
    "Did you hear about the guy who invented the knock knock joke?\nHe won the 'no-bell' prize",
    "Is this pool safe for diving?\nIt deep ends",
    "I used to hate facial hair,\nbut then it grew on me",
    "What do you call a fake noodle?\nAn Impasta",
    "Can February March?\nNo, but April May",
    "Wanna hear a joke about paper?\nNevermind, it's tearable",
    "Don't trust atoms\nThey make up everything",
    "How many apples grow on a tree?\nAll of them",
    "What do you call somebody with no body and no nose?\nNobody knows",
    "What did the buffalo say to his son when he left for college?\nBison",
    "What do you call a pony with a sore throat?\nA little horse",
    "I bought shoes from a drug dealer once\nI don't know what he laced them with, but I was tripping all day",
    "Where do you learn to make ice cream?\nSunday school",
    "What did the officer molecule say to the suspect molecule?\nI've got my ion you",
    "If prisoners could take their own mug shots,\nthey'd be called cellfies",
    "Why can't you hear a pterodactyl go to the bathroom?\nBecause the pee is silent",
    "I'm not addicated to brake fluid\nI can stop whenever I want",
    "Why did the coffee file a police report?\nIt got mugged",
    "Did you hear about the restaurant on the moon?\nGreat food, no atmosphere",
    "I hate jokes about german sausages\nThey're the wurst",
    "Why did the can-crusher quit his job?\nBecause it was soda-pressing",
    "I wouldn't buy anything with velcro\nIt's a total rip-off",
    "Dad, can you put the cat out?\nI didn't know it was on fire",
    "This graveyard looks overcrowded,\npeople must be dying to get in there",
    "Dad, can you put my shoes on?\nI don't think they'll fit me",
    "Dad, did you get a haircut?\nNo I got them all cut",
    "Have you heard of the band 1023MB?\nThey haven't got a gig yet",
]

@conf.debug
async def cmd_joke(message):
    """Show random joke.
    Usage: `joke`
    """
    conf.logger.debug("Invoked joke by user {}".format(message.author.name))
    return await message.channel.send(mf.info(random.choice(jokes_list)))

