# coding: utf-8

"""
    SQE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import qumranica_api_connector
from qumranica_api_connector.models.batch_updated_artefact_transform_dto import BatchUpdatedArtefactTransformDTO  # noqa: E501
from qumranica_api_connector.rest import ApiException

class TestBatchUpdatedArtefactTransformDTO(unittest.TestCase):
    """BatchUpdatedArtefactTransformDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BatchUpdatedArtefactTransformDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = qumranica_api_connector.models.batch_updated_artefact_transform_dto.BatchUpdatedArtefactTransformDTO()  # noqa: E501
        if include_optional :
            return BatchUpdatedArtefactTransformDTO(
                artefact_placements = [
                    qumranica_api_connector.models.updated_artefact_placement_dto.UpdatedArtefactPlacementDTO(
                        placement_editor_id = 56, 
                        artefact_id = 56, 
                        is_placed = True, 
                        placement = null, )
                    ]
            )
        else :
            return BatchUpdatedArtefactTransformDTO(
                artefact_placements = [
                    qumranica_api_connector.models.updated_artefact_placement_dto.UpdatedArtefactPlacementDTO(
                        placement_editor_id = 56, 
                        artefact_id = 56, 
                        is_placed = True, 
                        placement = null, )
                    ],
        )

    def testBatchUpdatedArtefactTransformDTO(self):
        """Test BatchUpdatedArtefactTransformDTO"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
