# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcb_web_auth', '0002_auto_20170512_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManagerConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='https://groups.oit.duke.edu/grouper-ws/servicesRest/json/v2_1_500', help_text='base grouper url', max_length=255)),
                ('account_id', models.IntegerField(help_text='duke unique id to use to connect to grouper')),
                ('password', models.CharField(help_text='password associated with account_id', max_length=255)),
            ],
        ),
    ]
