# coding: utf-8

"""
    SQE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from qumranica.configuration import Configuration


class SignInterpretationDTO(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'sign_interpretation_id': 'int',
        'next_sign_interpretations': 'list[NextSignInterpretationDTO]',
        'attributes': 'list[InterpretationAttributeDTO]',
        'rois': 'list[InterpretationRoiDTO]',
        'commentary': 'CommentaryDTO',
        'character': 'str',
        'is_variant': 'bool'
    }

    attribute_map = {
        'sign_interpretation_id': 'signInterpretationId',
        'next_sign_interpretations': 'nextSignInterpretations',
        'attributes': 'attributes',
        'rois': 'rois',
        'commentary': 'commentary',
        'character': 'character',
        'is_variant': 'isVariant'
    }

    def __init__(self, sign_interpretation_id=None, next_sign_interpretations=None, attributes=None, rois=None, commentary=None, character=None, is_variant=None, local_vars_configuration=None):  # noqa: E501
        """SignInterpretationDTO - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._sign_interpretation_id = None
        self._next_sign_interpretations = None
        self._attributes = None
        self._rois = None
        self._commentary = None
        self._character = None
        self._is_variant = None
        self.discriminator = None

        self.sign_interpretation_id = sign_interpretation_id
        self.next_sign_interpretations = next_sign_interpretations
        self.attributes = attributes
        self.rois = rois
        self.commentary = commentary
        self.character = character
        self.is_variant = is_variant

    @property
    def sign_interpretation_id(self):
        """Gets the sign_interpretation_id of this SignInterpretationDTO.  # noqa: E501


        :return: The sign_interpretation_id of this SignInterpretationDTO.  # noqa: E501
        :rtype: int
        """
        return self._sign_interpretation_id

    @sign_interpretation_id.setter
    def sign_interpretation_id(self, sign_interpretation_id):
        """Sets the sign_interpretation_id of this SignInterpretationDTO.


        :param sign_interpretation_id: The sign_interpretation_id of this SignInterpretationDTO.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and sign_interpretation_id is None:  # noqa: E501
            raise ValueError("Invalid value for `sign_interpretation_id`, must not be `None`")  # noqa: E501

        self._sign_interpretation_id = sign_interpretation_id

    @property
    def next_sign_interpretations(self):
        """Gets the next_sign_interpretations of this SignInterpretationDTO.  # noqa: E501


        :return: The next_sign_interpretations of this SignInterpretationDTO.  # noqa: E501
        :rtype: list[NextSignInterpretationDTO]
        """
        return self._next_sign_interpretations

    @next_sign_interpretations.setter
    def next_sign_interpretations(self, next_sign_interpretations):
        """Sets the next_sign_interpretations of this SignInterpretationDTO.


        :param next_sign_interpretations: The next_sign_interpretations of this SignInterpretationDTO.  # noqa: E501
        :type: list[NextSignInterpretationDTO]
        """
        if self.local_vars_configuration.client_side_validation and next_sign_interpretations is None:  # noqa: E501
            raise ValueError("Invalid value for `next_sign_interpretations`, must not be `None`")  # noqa: E501

        self._next_sign_interpretations = next_sign_interpretations

    @property
    def attributes(self):
        """Gets the attributes of this SignInterpretationDTO.  # noqa: E501


        :return: The attributes of this SignInterpretationDTO.  # noqa: E501
        :rtype: list[InterpretationAttributeDTO]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this SignInterpretationDTO.


        :param attributes: The attributes of this SignInterpretationDTO.  # noqa: E501
        :type: list[InterpretationAttributeDTO]
        """
        if self.local_vars_configuration.client_side_validation and attributes is None:  # noqa: E501
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    @property
    def rois(self):
        """Gets the rois of this SignInterpretationDTO.  # noqa: E501


        :return: The rois of this SignInterpretationDTO.  # noqa: E501
        :rtype: list[InterpretationRoiDTO]
        """
        return self._rois

    @rois.setter
    def rois(self, rois):
        """Sets the rois of this SignInterpretationDTO.


        :param rois: The rois of this SignInterpretationDTO.  # noqa: E501
        :type: list[InterpretationRoiDTO]
        """
        if self.local_vars_configuration.client_side_validation and rois is None:  # noqa: E501
            raise ValueError("Invalid value for `rois`, must not be `None`")  # noqa: E501

        self._rois = rois

    @property
    def commentary(self):
        """Gets the commentary of this SignInterpretationDTO.  # noqa: E501


        :return: The commentary of this SignInterpretationDTO.  # noqa: E501
        :rtype: CommentaryDTO
        """
        return self._commentary

    @commentary.setter
    def commentary(self, commentary):
        """Sets the commentary of this SignInterpretationDTO.


        :param commentary: The commentary of this SignInterpretationDTO.  # noqa: E501
        :type: CommentaryDTO
        """

        self._commentary = commentary

    @property
    def character(self):
        """Gets the character of this SignInterpretationDTO.  # noqa: E501


        :return: The character of this SignInterpretationDTO.  # noqa: E501
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this SignInterpretationDTO.


        :param character: The character of this SignInterpretationDTO.  # noqa: E501
        :type: str
        """

        self._character = character

    @property
    def is_variant(self):
        """Gets the is_variant of this SignInterpretationDTO.  # noqa: E501


        :return: The is_variant of this SignInterpretationDTO.  # noqa: E501
        :rtype: bool
        """
        return self._is_variant

    @is_variant.setter
    def is_variant(self, is_variant):
        """Sets the is_variant of this SignInterpretationDTO.


        :param is_variant: The is_variant of this SignInterpretationDTO.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and is_variant is None:  # noqa: E501
            raise ValueError("Invalid value for `is_variant`, must not be `None`")  # noqa: E501

        self._is_variant = is_variant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignInterpretationDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SignInterpretationDTO):
            return True

        return self.to_dict() != other.to_dict()
