
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-09T14:19:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "38244b16f82efa9a9955430c3c22221be41a5c0e",
 "version": "1.63.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
