# Generated by Django 2.0.8 on 2018-12-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('view_moonstuff', 'Can access the moonstuff module.'),)},
        ),
    ]
