# Generated by Django 3.1.2 on 2020-10-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivetask',
            name='exclude_fields',
            field=models.JSONField(blank=True, help_text='["play_type_name", "play_radio_name", "try_count"]'),
        ),
        migrations.AlterField(
            model_name='archivetask',
            name='extra_fields',
            field=models.JSONField(blank=True, help_text='["user__username", "user__profile__ref_user_id"]'),
        ),
        migrations.AlterField(
            model_name='archivetask',
            name='select_related',
            field=models.JSONField(blank=True, help_text='["user", "user__profile"]'),
        ),
    ]
