# Generated by Django 2.2.16 on 2020-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_community', '0004_auto_20201012_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control'), 'verbose_name': 'community', 'verbose_name_plural': 'communities'},
        ),
        migrations.AlterModelOptions(
            name='communitycircle',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control'), 'verbose_name': 'community circle', 'verbose_name_plural': 'community circles'},
        ),
        migrations.AlterModelOptions(
            name='communityjoboffer',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control'), 'verbose_name': 'community job offer', 'verbose_name_plural': 'community job offers'},
        ),
        migrations.AlterModelOptions(
            name='communitymember',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control'), 'verbose_name': 'community member', 'verbose_name_plural': 'community members'},
        ),
        migrations.AlterModelOptions(
            name='communityproject',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control'), 'verbose_name': 'community project', 'verbose_name_plural': 'community projects'},
        ),
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
