
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-16T17:32:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "063fb1de2764ad07951cd7ffd1d35a053e9f8053",
 "version": "0.8.214"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
