# Generated by Django 3.1.1 on 2020-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0002_auto_20200918_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturepost',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
