from SpellCorrect import input_processing,standard_owner,standard_sector
from Organize_Names import Corpus_Combo
from Import_corpus import input_file
from Get_Synonyms import Get_SynResult_function,Get_SynResult_function