# Generated by Django 2.2.16 on 2020-10-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_joboffer', '0007_auto_20200924_1937'),
        ('djangoldp_circle', '0023_auto_20200617_1817'),
        ('djangoldp_project', '0014_auto_20200903_1051'),
        ('djangoldp_community', '0003_communitycircles_communityjoboffers_communitymember_communityprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityCircles',
            new_name='CommunityCircle',
        ),
        migrations.RenameModel(
            old_name='CommunityJobOffers',
            new_name='CommunityJobOffer',
        ),
        migrations.RenameModel(
            old_name='CommunityProjects',
            new_name='CommunityProject',
        ),
    ]
