# Generated by Django 2.2.16 on 2020-10-12 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_community', '0005_auto_20201012_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
