# -*- coding: utf-8 -*-
from setuptools import setup

modules = \
['ntfy_synologychat']
install_requires = \
['requests>=2.24.0,<3.0.0']

setup_kwargs = {
    'name': 'ntfy-synologychat',
    'version': '0.2.0',
    'description': 'Synology Chat backend for ntfy',
    'long_description': '# ntfy-synologychat\n\nSynology Chat backend for ntfy.\n\n## Usage\n\n``` yaml\nntfy_synologychat:\n    webhook_url: ...\n    verify: false\n```\n\nRequired parameters:\n\n- `webhook_url` - string, a incoming webhook url generated by Synology Chat.\n\nOptional parameters:\n\n- `verify` - bool, whether verify https connection.\n',
    'author': 'Cologler',
    'author_email': 'skyoflw@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/Cologler/ntfy-synologychat-python',
    'py_modules': modules,
    'install_requires': install_requires,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)
